### ISSUE TITLE
Missing mapping for the "inProgress" state

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#18]
**Describe the bug**
A valid answer from the server ends up as an error (`Unknown LOCKSS state inProgress`) due to a missing mapping.

Screenshots can be seen at the origin:
https://forum.pkp.sfu.ca/t/pkp-pn-plugin-error-unknown-lockss-state-inprogress-eventhough-journal-issues-appear-on-the-list-of-journal-list-spreadsheet/72150/7

PRs
- https://github.com/pkp/pln/pull/15
- https://github.com/pkp/pln/pull/17

**What application are you using?**
OJS 3.3.0-10

**Comment by jonasraoni** [comment]
@asmecher Just a small PR to address this issue, I've been seeing it often in the forum, then I'll port it back for the older branches.
- https://github.com/pkp/pln/pull/15

**Comment by asmecher** [comment]
Merged https://github.com/pkp/pln/pull/15 for `main`, thanks! Please back-port to `stable-3_3_0`, but no further back than that.

FYI, I've just enabled Issues over on the PKP|PN plugin repository (https://github.com/pkp/pln/issues). Feel free to start tracking issues there.

**Comment by jonasraoni** [comment]
Ok, so here goes the one for `stable-3_3_0`
- https://github.com/pkp/pln/pull/17

**Comment by asmecher** [comment]
@jonasraoni, FYI, I've transferred this issue from pkp/pkp-lib, and created 2.0.4-3 and 3.0.0.0 milestones in this repo. I've assigned this issue to 2.0.4-3, which is the first release it'll be included in.

**Comment by jonasraoni** [comment]
@asmecher Please, give me some permissions, I can't set the milestones, assign myself to issues, etc.

Just to confirm, we'll be accumulating several issues into a release, right? Then, when are you planning to release them? Together with the OJS?

This issue needs to be moved to this repository as well: pkp/pln#22

**Comment by asmecher** [comment]
@jonasraoni, I've added you as a maintainer to the pln repository. Yes, we'll accumulate several fixes into each release. No need to release plugins along with e.g. the OJS release schedule. Normally a new release would either be triggered by a major issue in the plugin, or by the accumulation of enough smaller issues to make it worthwhile; it's discretionary.
