### ISSUE TITLE
Enable external access to the plugin URLs for private journals

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#19]
**Describe the problem you would like to solve**
When a journal is protected by login or non-public (e.g. perhaps preparing to retire), the staging server is unable to request the URL `gateway/plugin/PLNGatewayPlugin`

**Describe the solution you'd like**
Allow any custom URL of the plugin to passthrough.

**PRs**
- `stable-3_3_0`
- https://github.com/pkp/pln/pull/29
- https://github.com/pkp/pkp-lib/pull/8001
- https://github.com/pkp/ojs/pull/3427

- `main`
- https://github.com/pkp/pln/pull/16
- https://github.com/pkp/pkp-lib/pull/8002
- https://github.com/pkp/ojs/pull/3428

**Who is asking for this feature?**
Forum: https://forum.pkp.sfu.ca/t/ojs-3-3-0-10-pkp-pn-bad-request-error/73058/8

**Comment by jonasraoni** [comment]
@asmecher The purpose of this PR is to ensure the internal plugin routes are accessible when the journal's content is protected by login.
- https://github.com/pkp/pln/pull/16

Also, let me know if I should port it back to all branches.

**Comment by jonasraoni** [comment]
Meanwhile I'll check if the PKP PN is making use of other journal URLs, out of the plugin context.
Edit: No signal

**Comment by jonasraoni** [comment]
A user just confirmed that making the journal public fixed the issue, so these updates should be enough.

**Comment by jonasraoni** [comment]
@asmecher I've created an extra PR to add the hook to OJS and updated the other PRs.

**Comment by jonasraoni** [comment]
@asmecher Just a reminder, that these PRs are ready 😁

**Comment by asmecher** [comment]
All merged, thanks!
