### ISSUE TITLE
Update the plugin to communicate with the staging server through HTTPS

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#24]
Once the certificate gets setup in the staging server, ensure the plugin requests are under HTTPS by updating the base address to https://pkp-pn.lib.sfu.ca.

Note: The staging server cannot make use of auto-redirections from HTTP to HTTPS, as older plugin versions were making use of CURL, which won't follow redirections (plus, POST/PUT might get lost after the redirect).

**PRs**
- https://github.com/pkp/pln/pull/32
- https://github.com/pkp/pln/pull/33

**Comment by jonasraoni** [comment]
The PRs cannot be merged yet, there's some underlying infrastructure work being done, so I've marked them as drafts.

**Comment by jonasraoni** [comment]
The infrastructure work is done, the [new domain](https://pkp-pn.lib.sfu.ca) is already pointing to the existing server, and the SSL certificate was issued.
I've also tested the plugin locally against it and the requests/responses worked fine.

@asmecher now these PRs can be merged:
- https://github.com/pkp/pln/pull/32
- https://github.com/pkp/pln/pull/33

**Comment by asmecher** [comment]
Both merged, thanks! Can this issue be closed now or would you like to wait until after the server migration?

**Comment by jonasraoni** [comment]
I've asked to keep both domains active and pointing to the same place, otherwise the old plugins won't be able to communicate with the staging server.
