### ISSUE TITLE
Remove the PEAR/Archive_Tar requirement

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#25]
Some users have been complaining in the forum about a missing requirement "Your system must have a tar executable".
Given the package `whikloj/bagittools` already includes the PEAR package by itself composer, we don't need to check this requirement and the message might be removed to avoid confusions.

**PRs**
- https://github.com/pkp/pln/pull/30
- https://github.com/pkp/pln/pull/31

**Comment by jonasraoni** [comment]
@asmecher Here I've just removed the TAR requirement (we're not using it directly and the `bagittools` already includes such dependency to feed itself).

**PRs**
- https://github.com/pkp/pln/pull/30
- https://github.com/pkp/pln/pull/31

**Comment by asmecher** [comment]
Looks good, I've merged both PRs -- but in retrospect I should've asked first. What does the PKP|PN staging server do with the `tarInstalled` status in the ping? If the requirement will no longer be sent to the staging server, are there any checks that will start generating errors/warnings?

**Comment by jonasraoni** [comment]
@asmecher I've checked this before removing, and the staging server isn't using most of the data provided by the ping.
Perhaps it was added as a way to spy/debug if the installation has everything that's needed without asking to the user 🤔

**Comment by eddoff** [comment]
I read the thread https://forum.pkp.sfu.ca/t/ojs3-3-0-6-pkp-pn-plugin-warning-your-system-must-have-a-tar-executable/70273/7 because we have the same problem. However, I cannot find how to install this update, and I don't have access to Composer. To download the zip om the main branch from Git unpack that on the server did not work. Is there soon a new release that could be downloaded?

/eddoff

**Comment by jonasraoni** [comment]
If you don't have `composer` on your server, an alternative would be to generate the `tar.gz` with the dependencies on your machine.

**Comment by eddoff** [comment]
Do you have a link to a guide how to do that?

**Comment by jonasraoni** [comment]
There's [some documentation](https://docs.pkp.sfu.ca/dev/plugin-guide/en/release), but it doesn't cover your case. The process is simple, but better to ask for help on the forum, here we're just handling triaged issues.

**Comment by eddoff** [comment]
Isn't it time for a new release soon? It will then be much easier for us to upgrade via the plugin gallery instead.

**Comment by jonasraoni** [comment]
Hi @eddoff,

We had issues within the Preservation Network, so I decided to delay the new release, as it would increase the number of received deposits and make things worse. Now that everything's ok, I'm just waiting for a review here: https://github.com/pkp/pln/issues/28

Then a new release will happen.
