### ISSUE TITLE
Problem to generate deposits on Windows

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#26]
The underlying [package used to generate BagIt files](https://github.com/whikloj/BagItTools) has path issues when running under Windows, which breaks the plugin functionality.

Source: https://forum.pkp.sfu.ca/t/pkp-pln-plugin-produce-error/69900

At this moment, there isn't another library to replace it in GitHub.
If an upstream fix cannot be used in older branches, it's still possible to fix locally through a [composer patch](https://packagist.org/packages/cweagans/composer-patches).

**PRs**
- `stable-3_3_0` https://github.com/pkp/pln/pull/38
- `main` https://github.com/pkp/pln/pull/37

**Comment by jonasraoni** [comment]
Update: I've fixed the issues and submitted a PR here: https://github.com/whikloj/BagItTools/issues/45

Once it gets merged, this might be back ported only to OJS 3.3.0, because the package is based on PHP 7.3.

**Comment by jonasraoni** [comment]
The changes have been merged upstream, so we just need to wait for a release.

**Comment by jonasraoni** [comment]
@asmecher a new BagItTools package with the updates I did was released

**PRs**
- `stable-3_3_0` https://github.com/pkp/pln/pull/38
- `main` https://github.com/pkp/pln/pull/37

**Comment by asmecher** [comment]
(Reviewed the `stable-3_3_0` PR above -- see [note on competing Composer dependencies](https://github.com/pkp/pln/pull/38#discussion_r907570148).)

**Comment by jonasraoni** [comment]
Just confirming that the fix has solved the problem for an user using OJS 3.3.0-8:
https://forum.pkp.sfu.ca/t/re-ojs-3-3-0-8-pkp-pln-errors/73866

**Comment by jonasraoni** [comment]
@asmecher FYI I've disabled the `prepend-autoloader`, that should be enough to address the conflict issue, at least for this plugin.

There are other options at the [conflict solving discussion](https://github.com/pkp/pkp-lib/discussions/8106) that I can add later.

**Comment by jonasraoni** [comment]
Merged PRs at the top.
