### ISSUE TITLE
Class 'APP\notification\Notification' not found

### ISSUE THREAD

**Issue by azamat5991** [pkp/pln#36]
After installing the plugin manually according to instructions, plugin gallery stuck at loading.
From the console I'm getting this error: 

`"GET https://myjournal.com/index.php/tech/$$$call$$$/grid/settings/plugins/settings-plugin-grid/fetch-grid?_=1655654133139 500"
`
And from php logs I see this:
```
"PHP message: PHP Fatal error:  Uncaught Error: Class 'APP\notification\Notification' not found in /var/www/vhosts/myjournal.com/httpdocs/plugins/generic/pln-main/PLNPlugin.inc.php:72
Stack trace:
#0 /var/www/vhosts/myjournal.com/httpdocs/plugins/generic/pln-main/index.php(13): require_once()
#1 /var/www/vhosts/myjournal.com/httpdocs/lib/pkp/classes/plugins/PluginRegistry.inc.php(241): include('/var/www/vhosts...')
#2 /var/www/vhosts/myjournal.com/httpdocs/lib/pkp/classes/plugins/PluginRegistry.inc.php(126): PluginRegistry::_instantiatePlugin('generic', 'plugins/generic', 'pln-main')
#3 /var/www/vhosts/myjournal.com/httpdocs/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(155): PluginRegistry::loadCategory('generic')
#4 /var/www/vhosts/myjournal.com/httpdocs/controllers/grid/settings/plugins/SettingsPluginGridHandler.inc.php(36): PluginGridHandler->loadCategoryData(Object(Request), 'generic', Array)
#5 /var/www/vhosts/myjournal.com/httpdocs/lib/pkp/classes/controllers/grid/CategoryGridHa" while reading response header from upstream, client: 95.91.235.178, server: myjournal.com, request: "GET /index.php/tech/$$$call$$$/grid/settings/plugins/settings-plugin-grid/fetch-grid?_=1655648407476 HTTP/2.0", upstream: "fastcgi://unix:/var/www/vhosts/system/myjournal.com/php-fpm.sock:", host: "myjournal.com", referrer: "https://myjournal.com/index.php/tech/management/settings/website"
```

What can be the cause of this error?

**Comment by jonasraoni** [comment]
Hi @azamat5991!

Have you installed the `/main` branch of the plugin against an OJS <= 3.3.0? If yes, that's not going to work, the `/main` branch is currently a work in progress to support OJS 3.4. Here you can see all the branches: https://github.com/pkp/pln/branches

Didn't you see any errors in the log when you tried to install through the plugin gallery? If you can, please also check the console log of the browser (by pressing F12).

Best,
Jonas

**Comment by jonasraoni** [comment]
I'm closing this issue, but if my answer doesn't reflect your situation, I can reopen :)

**Comment by azamat5991** [comment]
Hi @jonasraoni ,
thank you for your answer. After intalling version 3.3 it's loading ok.
But the issue now is when I click Status, plugin shows this error
`GET https://myjoundal.com/index.php/tech/$$$call$$$/plugins/generic/pln/controllers/grid/p-l-n-status-grid/fetch-grid?_=1656273050342 404`

**Comment by jonasraoni** [comment]
Thanks for the report, I've [seen this error in the forum once](https://forum.pkp.sfu.ca/t/error-en-el-proceso-de-deposito-de-pkp-preservation-network/67005), but I thought the user was just using an old/broken version.

What's exactly the OJS version that you're using?
If possible also tell me the OS and web server too 😁

**Comment by azamat5991** [comment]
I'm using OJS version 3.3.0.7

**Comment by jonasraoni** [comment]
Just for reference, the issue here is that the plugin was installed in the wrong location, it should be placed exactly at `plugins/generic/pln`.
