### ISSUE TITLE
Plugin installed but not visible

### ISSUE THREAD

**Issue by vebaev** [pkp/pln#39]
Dear all,

I have a problem with the plugin. Our OJS 3.1.2 says the plugin (v2.0.1.1) is installed but it is not visible in the Installed plugins tab at all. I also see an Archiving tab where when I click enable PKP PN, it refreshes and nothing happens.

Can you assist to resolve the issue?

**Comment by jonasraoni** [comment]
Hi @vebaev!

We're trying to keep the discussions inside the forum, until we're sure they are bugs, so I'll be closing this issue, and offer some support through the forum topic that you've opened: https://forum.pkp.sfu.ca/t/pkp-pn-plugin-say-installed-in-galley-but-missing-in-installed-plugins/73826/7
