### ISSUE TITLE
PHP 8.0.25 complains about non-static method getting called statically

### ISSUE THREAD

**Issue by nwoodward** [pkp/pln#43]
There are errors in the plugin cron jobs that look related to using PHP 8.0. We're on the most recent version of the plugin (2.0.4-2).

`PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in /ojs/plugins/generic/pln/classes/DepositPackage.inc.php:133\nStack trace:\n#0 /ojs/plugins/generic/pln/classes/DepositPackage.inc.php(556): DepositPackage->generateAtomDocument()\n#1 /ojs/plugins/generic/pln/classes/tasks/Depositor.inc.php(225): DepositPackage->packageDeposit()\n#2 /ojs/plugins/generic/pln/classes/tasks/Depositor.inc.php(127): Depositor->_processNeedPackaging(Object(Journal))\n#3 /ojs/lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(146): Depositor->executeActions()\n#4 /ojs/lib/pkp/plugins/generic/acron/PKPAcronPlugin.inc.php(258): ScheduledTask->execute()\n#5 [internal function]: PKPAcronPlugin->shutdownFunction()\n#6 {main}\n  thrown in /ojs/plugins/generic/pln/classes/DepositPackage.inc.php on line 133`

**Comment by jonasraoni** [comment]
Linked PRs merged.

@nwoodward Thanks for the report! The update will be available once a new version is released. If you need it ASAP, you might install the plugin manually (the instructions are available on the README.md).

**Comment by nwoodward** [comment]
That's great news. Thanks!
