### ISSUE TITLE
Hi, the name of files in our server has a slight diff PN instead of PLN : PKPPNDepositorTask-id-date.log

### ISSUE THREAD

**Issue by pablogit** [pkp/pln#44]
https://github.com/pkp/pln/blob/d13bbc15be0c80b89d89689dfa26a5d220380036/README.md?plain=1#L96

**Comment by jonasraoni** [comment]
Thanks for warning, soon we'll rename everything to PN (there's a note here: https://github.com/pkp/pln/issues/21) :)

So I'll close this as a duplicate.
