### ISSUE TITLE
OJS User - Author - "Country" field 

### ISSUE THREAD

**Issue by mikoko1** [pkp/pln#80]
OJS 3.3.0.10
When creating a user who is "Author" (which is unlike all other user roles), the "Country" field is mandatory.
When it is empty, we get the message: "This field is required."
However, in rare cases where a journal or author is not interested in using this field, it should be left blank. 
How can we fix this problem?

**Comment by jonasraoni** [comment]
Hi @mikoko1!

I'll close this issue as it's not related to this repository.
On a second note, we're reserving the GitHub issues for strictly technical/internal issues, so you're not going to get much help here. It's better to use the forum, there's a "feature request" section here: https://forum.pkp.sfu.ca/c/feature-requests/8
