### ISSUE TITLE
PHP warning about missing autoload.php file

### ISSUE THREAD

**Issue by nwoodward** [pkp/pln#93]
> PHP Warning:  require_once(/ojs/journal1/plugins/generic/pln/classes/../vendor/autoload.php): Failed to open stream: No such file or directory in /ojs/journal1/plugins/generic/pln/classes/DepositPackage.php on line 234

I see this error repeated in the Apache logs, and I think it's just a path issue with the plugin not finding `autoload.php` on line https://github.com/pkp/pln/blob/stable-3_4_0/classes/DepositPackage.php#L234 when it tries to create a package. I'm not sure if it's a big deal, but I thought I would mention it.

The journal is on OJS version 3.4.0-5 with version v3_0_0-0 of the PKP|PN plugin and PHP 8.1.

**Comment by jonasraoni** [comment]
Hi!

This file should exist if you install the plugin through the plugin gallery or one of the packages available at https://github.com/pkp/pln/releases.

If you've cloned the repository, then an extra step is needed, to run the `composer install`.

I'll close this one for now, feel free to reopen if something doesn't make sense.
